### ISSUE TITLE
[feature-request] Email subject filtering

### ISSUE THREAD

**Issue by pscriptos** [seb1k/imap-ntfy#1]
Hello,

Thank you very much for your great script. 
I'm not using it yet, but I'll start using it today.

I have a feature request for you:

I would love it if the emails could be sorted by ‘subject’ into different topics.

Example:

The subject starts with `[service1] I am an alarm`, then the script can forward the message to topic `/service1`.

Now the subject starts with `[service2] I am a message`, then the message can be forwarded to topic `/service2`.

Thank you very much and have a nice weekend! :)

Patrick

**Comment by seb1k** [comment]
Too specific case to be added.
Subject start checking not easy to check depending of the charset.
